---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:latest
    volumes:
      - name: deps
        path: /go
    commands:
      - go get -u github.com/gobuffalo/packr/...
      - packr build

  - name: linter
    image: golang:latest
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s
      - ./bin/golangci-lint run

  - name: telegram
    image: appleboy/drone-telegram
    settings:
      to: 790376882
      format: markdown
      token:
        from_secret: telegram_token
    when:
      status:
        - success
        - failure

volumes:
  - name: deps
    host:
      path: /var/lib/cache/godeps/
